[package]
name = "mux-stream"
version = "0.1.0"
authors = ["Temirkhan Myrzamadi <hirrolot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-core", "rt-threaded", "sync", "stream", "macros"] }
futures = "0.3"
trybuild = "1.0"
